### PR TITLE
Add transition_from matcher

### PR DESCRIPTION
**Pull request by vtm9**
Add useful matcher: 'transition_from'

### CODE REVIEW

**Comment by vtm9** [comment]
Can you merge it?

**Comment by rosskevin** [comment]
I have requested push access from @JohnSmall

**Comment by vtm9** [comment]
@rosskevin, Thanks. Can anybody update version and update it on rubygems?

**Comment by SirRawlins** [comment]
@rosskevin @vtm9 great feature, using this myself today. At first was confused as was getting error `Method transition_from does not exist` - then realised Rubygems wasn't up to date, so had to pull from Github instead.

Another thing of note is that `transition_from` only appears to work on instances, and not at a class level as the README would suggest from the examples.

Is this by design? Should we update the README, or is this a bug in the code?

**Comment by rosskevin** [comment]
I have sent @JohnSmall another email requesting push access.

**Comment by vtm9** [comment]
@SirRawlins In README  we use  rspec [implicitly-defined-subject](https://relishapp.com/rspec/rspec-core/v/3-5/docs/subject/implicitly-defined-subject#`subject`-exposed-in-top-level-group).

**Comment by SirRawlins** [comment]
Thanks Vitaly, that makes perfect sense.

**Comment by seuros** [comment]
v0.4.0 is released : https://rubygems.org/gems/state_machines-rspec

**Pull request merged**
